version: '3.8'

services:
  # Redis Servisi (Veritabanı ve Mesaj Aracısı)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Backend Servisi (Flask API)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app  # Kod değişikliklerinin anında yansıması için
    ports:
      - "5001:5001"
    command: python3 app.py
    depends_on:
      - redis
    restart: unless-stopped

  # Celery Worker Servisi (İşçi)
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - backend
    restart: unless-stopped

  # Celery Beat Servisi (Zamanlayıcı)
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    command: celery -A celery_worker.celery_app beat --loglevel=info
    depends_on:
      - redis
      - backend
    restart: unless-stopped

  # Frontend Servisi (React Arayüzü)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Bu satır, local node_modules'in üzerine yazılmasını engeller
    ports:
      - "5173:5173"
    restart: unless-stopped